apiVersion: v1
kind: Service
metadata:
  name: chrome
  namespace: {{ .Values.system.namespace }}
spec:
  type: NodePort
  selector:
    app: chrome
  ports:
  - protocol: TCP
    port: 9222
    targetPort: 9222
